name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and push
      run: |
        docker build . --tag docker.pkg.github.com/oott123/docker-mediawiki/mediawiki:latest
        docker login docker.pkg.github.com -u oott123 -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/oott123/docker-mediawiki/mediawiki:latest
